Exploratory Data Aanlysis (EDA) has the following steps
1. Database exploration
2. Dimension exploration
3. Data exploration
4. Measure exploration 
5. Magnitude
6. Ranking : top N - bottom N


1st step of any project : explore the dataset
-- explore all objects in the database
select * from information_schema.tables;

-- explore all columns in the database
select * from information_schema.columns
where table_name = 'gold_dim_customers'

-- 2nd step - Dimention exploration
-- identify the unique values (or categories) in each dimension.
-- recognizing how data might be grouped or segmented, which is useful for later analysis.
-- very simple method to check that is by using the keyword 'distinct'. eg: DISTINCT country

select distinct country
from customers;

select distinct category, subcategory, product_name
from products
order by 1,2,3;


-- the following is helping us understand the number of years of data available in our dataset
-- find the date of the first and last order
select 
min(order_date)::date first_order, 
max(order_date)::date last_order
from sales 

-- how many years of sales are available?
select 
min(order_date)::date first_order, 
max(order_date)::date last_order,
-- datediff(year,min(order_date)) order_range  --- sql query and not postgres
EXTRACT(YEAR FROM MAX(order_date)) - EXTRACT(YEAR FROM MIN(order_date)) AS order_range
from sales 


-- find the youngest and the oldest customer
select 
min(birthdate)::date youngest_b,
-- datediff(year, min(birthdate), getdate()) oldest_age,  -- sql command 
EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM MIN(birthdate)) AS oldest_age,
EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM MAX(birthdate)) AS youngest_age,
max(birthdate)::date oldest_b
from customers


-- Measure exploration 
Calculate and find out the key metrics of the business(big numbers)
- highest level of aggregation | lowest level of aggregation
for ex: sum(sales), avg(price), sum(quantity), bascially aggregation of measure


-- Find the total sales
select * from sales; 
select 
sum(sales_amount) total_sales
from sales

-- Find how many items are sold
select
sum(quantity) sold_items
from sales


-- Find the avg selling price
select
round(avg(price)) avg_price
from sales

-- find the total number of orders
select 
count(order_number) count_order,
count(distinct order_number) dist_count -- to get accurate no. of orders and check the duplicates
from sales

-- Find the total number of products
select * from products;
select
count(product_key) total_prodcuts
from products

-- Find the total number of customers
select * from customers;
select 
count(customer_key) cust_count
from customers;

-- Find the total number of customers that has placed an order
select 
count(distinct customer_key) cust_sales
from sales;

The best to do the above measure calculation is the following:
-- Generate repport that shows all key metrics of the business 
build only two columns - > name of the measure and value of the measure 

select 
'Total Sales' as measure_name,  -- static value 
sum(sales_amount) measure_value 
from sales

UNION all

select 
'Total Quantity',  -- static value 
sum(quantity)
from sales

union all 

select
'Average Price',
round(avg(price))
from sales

union all

select 
'Total No.of Orders',
count(distinct order_number)  -- to get accurate no. of orders and check the duplicates
from sales

union all

select
'Total No.of Products',
count(product_key)
from products

union all

select 
'Total No.of Customers',
count(customer_key) 
from customers

union all 

select 
'Customers orders placed',
count(distinct customer_key)
from sales


-- Magnitude Analysis
Compare the measure values by categories.
It helps us understand the importance of different categories.
Aggregate[Measure] by Dimension 
ex: Total sales by country, total quantity by category, avg price by product, total orders by customer


-- Find the total customers by countries
select 
country,
count(customer_key) as total_cust
from customers
group by country
order by total_cust desc

-- find total customers by gender
select
gender,
count(customer_key)
from customers
group by gender

-- Find total products by category
select 
category,
count(product_key) total_prod
from products
group by category
order by total_prod desc

-- What is the avg costs in each category
select 
category,
round(avg(cost)) avg_cos
from products
group by category
order by avg_cos desc

-- What is the total revenue generated for each category
select 
p.category,
sum(s.sales_amount) category_revenue
from sales s
left join products p on p.product_key = s.product_key
group by p.category
order by category_revenue desc

-- Find total revenue is generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
sum(s.sales_amount) cust_spender
from sales s
left join customers c on c.customer_key = s.customer_key
group by c.customer_key,c.first_name, c.last_name
order by cust_spender desc 

-- What is the distribution of sold items across countries
select
c.country,
sum(s.quantity) total_sold_item
from sales s
left join customers c on c.customer_key = s.customer_key
group by c.country
order by total_sold_item desc


--Ranking Analysis - order the values of dimensions by measure. In order to identify top performers and bottom performers
formula: rank[dimension] by aggregated[measure]
ex: rank ountries by total sales, top 5 products by quantity, bottom 3 customers by total orders
we can use functions like rank, dense_rank, row_number

-- Which 5 products generate the highest revenue?
select 
p.product_name,
sum(s.sales_amount) category_revenue
from sales s
left join products p on p.product_key = s.product_key
group by p.product_name
order by category_revenue desc
limit 5 

-- the same thing which is above solved by using window functions
select *
from (       -- this is more complicated than the above solution but this is used when generating complex reports
    select 
    p.product_name,
    sum(s.sales_amount) category_revenue,
    row_number() over(order by sum(s.sales_amount) desc) rank_prod
    from sales s
    left join products p on p.product_key = s.product_key
    group by p.product_name
)
where rank_prod <=5

-- What are the 5 worst-performing products in terms of sales ?
select 
p.product_name,
sum(s.sales_amount) category_revenue
from sales s
left join products p on p.product_key = s.product_key
group by p.product_name
order by category_revenue
limit 5 

-- we can do this same thing for subcategories too

-- Find the top-10 customers who have generated the highest revenue and 3 customers with the fewest orders placed
select
c.customer_key,
c.first_name,
c.last_name,
sum(s.sales_amount) cust_spender
from sales s
left join customers c on c.customer_key = s.customer_key
group by c.customer_key,c.first_name, c.last_name
order by cust_spender desc 
limit 10

select
c.customer_key,
c.first_name,
c.last_name,
count(distinct order_number) tot_orders
from sales s
left join customers c on c.customer_key = s.customer_key
group by c.customer_key,c.first_name, c.last_name
order by tot_orders 
limit 3